name: github-to-gcpfunctions
on:
  push:
    branches:
      - main
jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: githubaction
          runtime: python38
          entry_point: telegram_bot
          env_vars: "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}"
          service_account_email: example-service-account@green-cell-329502.iam.gserviceaccount.com
      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
